apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: instana
  namespace: instana-elastic
spec:
  monitoring:
    logs: {}
    metrics: {}
  version: ${ELASTIC_VERSION}
  image: ${ELASTIC_IMAGE_NAME}
  nodeSets:
  - name: default
    count: 1
    podTemplate:
      metadata:
        creationTimestamp: null
      spec:
        serviceAccountName: elasticsearch
        # Add the following podAntiAffinity snippet to schedule each pod on a different node. 
        #affinity:
        #  podAntiAffinity:
        #    requiredDuringSchedulingIgnoredDuringExecution:
        #    - labelSelector:
        #        matchLabels:
        #          elasticsearch.k8s.elastic.co/cluster-name: instana
        #      topologyKey: kubernetes.io/hostname   
        imagePullSecrets:
          - name: instana-registry
        # nodeSelector:
        #   deploy-env: bank-prod
        containers:
        - name: elasticsearch
          #env:
          # - name: ES_JAVA_OPTS
          #   value: -Xms1g -Xmx1g
          #- name: ingest.geoip.downloader.enabled
          #  value: "false"
          resources:
            limits:
              memory: 3Gi
            requests:
              cpu: "1"
              memory: 2Gi
    config:
      node.master: true
      node.data: true
      node.ingest: true
      node.store.allow_mmap: false
      search.max_buckets: 65000
      xpack.ml.enabled: false
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data # Do not change this name unless you set up a volume mount for the data path.
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 200Gi
        storageClassName: ${RWO_STORAGECLASS}
  http:
    service:
      metadata: {}
      spec: {}
    tls:
      certificate: {}
      selfSignedCertificate:
        disabled: true