# Diffie-Hellman parameters to use (Optional)
#dhParams: |
#  <snip/>
# The download key you received from us
repositoryPassword: ${INSTANA_IMAGE_REGISTRY_PASSWORD}
# The sales key you received from us
salesKey: ${SALES_KEY}
# Seed for creating crypto tokens. Pick a random 12 char string
tokenSecret: ${TOKEN_SECRET}
# Configuration for raw spans storage
storageConfigs:
#  rawSpans:
#    # Required if using S3 or compatible storage bucket.
#    # Credentials should be configured.
#    # Not required if IRSA on EKS is used.
#    s3Config:
#      accessKeyId: ...
#      secretAccessKey: ...
#    # Required if using Google Cloud Storage.
#    # Credentials should be configured.
#    # Not required if GKE with workload identity is used.
#    gcloudConfig:
#      serviceAccountKey: ...

# SAML/OIDC configuration
# serviceProviderConfig:
#   # Password for the key/cert file
#   keyPassword: ${KEY_PEM_PASSWORD}
#   # The combined key/cert file
#   pem: |
#     <snip/>
# # Required if a proxy is configured that needs authentication
# proxyConfig:
#   # Proxy user
#   user: myproxyuser
#   # Proxy password
#   password: my proxypassword
# emailConfig:
#   # Required if SMTP is used for sending e-mails and authentication is required
#   smtpConfig:
#     user: mysmtpuser
#     password: mysmtppassword
#   # Required if using for sending e-mail.
#   # Credentials should be configured.
#   # Not required if using IRSA on EKS.
#   sesConfig:
#     accessKeyId: ...
#     secretAccessKey: ...
# # Optional custom CA certificate to be added to component trust stores
# # in case internal systems Instana talks to (e.g. LDAP or alert receivers) use a custom CA.
# customCACert: |
#   -----BEGIN CERTIFICATE-----
#   <snip/>
#   -----END CERTIFICATE-----
### datastoreConfigs added automatically with generated passwords