apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: instana-postgres
spec:
  instances: 3
  imageName: ${POSTGRES_IMAGE_NAME}:${POSTGRES_IMAGE_TAG}
  imagePullPolicy: IfNotPresent
  imagePullSecrets:
  - name: instana-registry
  postgresql:
    parameters:
      shared_buffers: 32MB
      pg_stat_statements.track: all
      auto_explain.log_min_duration: '10s'
    pg_hba:
      - local     all          all                            trust
      - host      all          all          0.0.0.0/0         md5
      - local     replication  standby                        trust
      - hostssl   replication  standby      all               md5
      - hostnossl all          all          all               reject
      - hostssl   all          all          all               md5
  managed:
    roles:
    - name: instanaadmin
      login: true
      superuser: true
      createdb: true
      createrole: true
      passwordSecret:
        name: instanaadmin
  bootstrap:
    initdb:
      database: instanaadmin
      owner: instanaadmin
      secret:
        name: instanaadmin
  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi
  superuserSecret:
    name: instanaadmin
  storage:
    size: 50Gi
    storageClass: ${RWO_STORAGECLASS}